import type { UserConfig } from 'cz-git'

const configuration: UserConfig = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'perf',
        'style',
        'docs',
        'test',
        'refactor',
        'build',
        'ci',
        'init',
        'chore',
        'revert',
        'wip',
        'workflow',
        'types',
        'release',
      ],
    ],
    'subject-case': [0],
  },
  prompt: {
    alias: {
      fd: 'docs: fix typos',
    },
    messages: {
      type: '选择你要提交的类型 :',
      scope: '选择一个提交范围（可选）:',
      customScope: '请输入自定义的提交范围 :',
      subject: '填写简短精炼的变更描述 :\n',
      body: '填写更加详细的变更描述（可选）。使用 "|" 换行 :\n',
      breaking: '列举非兼容性重大的变更（可选）。使用 "|" 换行 :\n',
      footerPrefixesSelect: '选择关联 issue 前缀（可选）:',
      customFooterPrefix: '输入自定义 issue 前缀 :',
      footer: '列举关联 issue（可选）例如: #31, #I3244 :\n',
      confirmCommit: '是否提交或修改 commit ?',
    },
    types: [
      { value: 'feat', name: 'feat: 新增功能' },
      { value: 'fix', name: 'fix: 修复问题' },
      { value: 'docs', name: 'docs: 文档更新' },
      { value: 'style', name: 'style: 代码格式' },
      { value: 'refactor', name: 'refactor: 代码重构' },
      { value: 'perf', name: 'perf: 性能优化' },
      { value: 'test', name: 'test: 测试相关' },
      { value: 'build', name: 'build: 构建相关' },
      { value: 'ci', name: 'ci: 持续集成' },
      { value: 'revert', name: 'revert: 回退代码' },
      { value: 'chore', name: 'chore: 杂项修改' },
    ],
    emojiAlign: 'center',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [
      { value: 'repo', name: 'repo: 仓库' },
      { value: 'cli', name: 'cli: 命令行' },
      { value: 'studio', name: 'studio: 工作台' },
      { value: 'ui', name: 'ui: 界面' },
      { value: 'server', name: 'server: 服务端' },
      { value: 'setup', name: 'setup: 初始化' },
      { value: 'quality', name: 'quality: 质量检查' },
      { value: 'lint', name: 'lint: 代码检查' },
      { value: 'build', name: 'build: 构建发布' },
      { value: 'hooks', name: 'hooks: 提交钩子' },
      { value: 'release', name: 'release: 版本发布' },
    ],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [
      { value: 'link', name: 'link:     链接 ISSUES 进行中' },
      { value: 'closed', name: 'closed:   标记 ISSUES 已完成' },
    ],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
}

export default configuration
