/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const FieldContextKey: typeof import('vee-validate').FieldContextKey
  const FormContextKey: typeof import('vee-validate').FormContextKey
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const cn: typeof import('../src/utils/tailwind').cn
  const computed: typeof import('vue').computed
  const configure: typeof import('vee-validate').configure
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineRule: typeof import('vee-validate').defineRule
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getLanguageLabel: typeof import('../src/constants/language').getLanguageLabel
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const languageOptions: typeof import('../src/constants/language').languageOptions
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const matchPathFilters: typeof import('../src/composables/path-query').matchPathFilters
  const matchPathQuery: typeof import('../src/composables/path-query').matchPathQuery
  const nextTick: typeof import('vue').nextTick
  const normalizePathQuery: typeof import('../src/composables/path-query').normalizePathQuery
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const regenerateIds: typeof import('../src/composables/useCollaboration').regenerateIds
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toast: typeof import('../src/utils/toast').toast
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCollaboration: typeof import('../src/composables/useCollaboration').useCollaboration
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useField: typeof import('vee-validate').useField
  const useFieldArray: typeof import('vee-validate').useFieldArray
  const useFieldError: typeof import('vee-validate').useFieldError
  const useFieldValue: typeof import('vee-validate').useFieldValue
  const useForm: typeof import('vee-validate').useForm
  const useFormErrors: typeof import('vee-validate').useFormErrors
  const useFormValues: typeof import('vee-validate').useFormValues
  const useId: typeof import('vue').useId
  const useInitForm: typeof import('../src/composables/useInitForm').useInitForm
  const useIsFieldDirty: typeof import('vee-validate').useIsFieldDirty
  const useIsFieldTouched: typeof import('vee-validate').useIsFieldTouched
  const useIsFieldValid: typeof import('vee-validate').useIsFieldValid
  const useIsFormDirty: typeof import('vee-validate').useIsFormDirty
  const useIsFormTouched: typeof import('vee-validate').useIsFormTouched
  const useIsFormValid: typeof import('vee-validate').useIsFormValid
  const useIsSubmitting: typeof import('vee-validate').useIsSubmitting
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useResetForm: typeof import('vee-validate').useResetForm
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useSubmitCount: typeof import('vee-validate').useSubmitCount
  const useSubmitForm: typeof import('vee-validate').useSubmitForm
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useValidateField: typeof import('vee-validate').useValidateField
  const useValidateForm: typeof import('vee-validate').useValidateForm
  const validate: typeof import('vee-validate').validate
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { TinyI18nPathFilterMode, TinyI18nPathFilter } from '../src/composables/path-query'
  import('../src/composables/path-query')
  // @ts-ignore
  export type { LanguageOption } from '../src/constants/language'
  import('../src/constants/language')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly FieldContextKey: UnwrapRef<typeof import('vee-validate')['FieldContextKey']>
    readonly FormContextKey: UnwrapRef<typeof import('vee-validate')['FormContextKey']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly cn: UnwrapRef<typeof import('../src/utils/tailwind')['cn']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly configure: UnwrapRef<typeof import('vee-validate')['configure']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineRule: UnwrapRef<typeof import('vee-validate')['defineRule']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getLanguageLabel: UnwrapRef<typeof import('../src/constants/language')['getLanguageLabel']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly languageOptions: UnwrapRef<typeof import('../src/constants/language')['languageOptions']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly matchPathFilters: UnwrapRef<typeof import('../src/composables/path-query')['matchPathFilters']>
    readonly matchPathQuery: UnwrapRef<typeof import('../src/composables/path-query')['matchPathQuery']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizePathQuery: UnwrapRef<typeof import('../src/composables/path-query')['normalizePathQuery']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly regenerateIds: UnwrapRef<typeof import('../src/composables/useCollaboration')['regenerateIds']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toast: UnwrapRef<typeof import('../src/utils/toast')['toast']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCollaboration: UnwrapRef<typeof import('../src/composables/useCollaboration')['useCollaboration']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useField: UnwrapRef<typeof import('vee-validate')['useField']>
    readonly useFieldArray: UnwrapRef<typeof import('vee-validate')['useFieldArray']>
    readonly useFieldError: UnwrapRef<typeof import('vee-validate')['useFieldError']>
    readonly useFieldValue: UnwrapRef<typeof import('vee-validate')['useFieldValue']>
    readonly useForm: UnwrapRef<typeof import('vee-validate')['useForm']>
    readonly useFormErrors: UnwrapRef<typeof import('vee-validate')['useFormErrors']>
    readonly useFormValues: UnwrapRef<typeof import('vee-validate')['useFormValues']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useInitForm: UnwrapRef<typeof import('../src/composables/useInitForm')['useInitForm']>
    readonly useIsFieldDirty: UnwrapRef<typeof import('vee-validate')['useIsFieldDirty']>
    readonly useIsFieldTouched: UnwrapRef<typeof import('vee-validate')['useIsFieldTouched']>
    readonly useIsFieldValid: UnwrapRef<typeof import('vee-validate')['useIsFieldValid']>
    readonly useIsFormDirty: UnwrapRef<typeof import('vee-validate')['useIsFormDirty']>
    readonly useIsFormTouched: UnwrapRef<typeof import('vee-validate')['useIsFormTouched']>
    readonly useIsFormValid: UnwrapRef<typeof import('vee-validate')['useIsFormValid']>
    readonly useIsSubmitting: UnwrapRef<typeof import('vee-validate')['useIsSubmitting']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useResetForm: UnwrapRef<typeof import('vee-validate')['useResetForm']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSubmitCount: UnwrapRef<typeof import('vee-validate')['useSubmitCount']>
    readonly useSubmitForm: UnwrapRef<typeof import('vee-validate')['useSubmitForm']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useValidateField: UnwrapRef<typeof import('vee-validate')['useValidateField']>
    readonly useValidateForm: UnwrapRef<typeof import('vee-validate')['useValidateForm']>
    readonly validate: UnwrapRef<typeof import('vee-validate')['validate']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}